module.exports.events = {
    'CREATE_GAME': 'CREATE_GAME',
    'JOIN_GAME':'JOIN_GAME',
    'CURRENT_PLAYERS_COUNT':'CURRENT_PLAYERS_COUNT',
    'START_GAME':'START_GAME',
    'IMPOSTER':'IMPOSTER',
    "PLAYER_TURN":'PLAYER_TURN'
}